name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
      
    - name: Create the TmEssentials package
      run: dotnet pack TmEssentials -c Release
    - name: Publish the TmEssentials package to nuget.org
      run: dotnet nuget push TmEssentials/bin/Release/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
    - name: Publish the TmEssentials package to github.com
      run: dotnet nuget push TmEssentials/bin/Release/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/bigbang1112/index.json
    - name: Attach the TmEssentials package to the release
      uses: svenstaro/upload-release-action@v2
      with:
        file: TmEssentials/bin/Release/*.nupkg
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true
