name: .NET

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create the TmEssentials package
      run: dotnet pack TmEssentials --configuration Release
    - name: Publish the TmEssentials package to nuget.org
      run: dotnet nuget push TmEssentials/bin/Release/*.nupkg -k $AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
    - name: Publish the TmEssentials package to github.com
      run: dotnet nuget push TmEssentials/bin/Release/*.nupkg -k $AUTH_TOKEN -s https://nuget.pkg.github.com/bigbang1112/index.json
      env:
        AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
